### ISSUE TITLE
Enhance type system

### ISSUE THREAD

**Issue by xu3u4** [ianlai/react-todo-app#1]
I can see `TodoType` in https://github.com/ianlai/react-todo-app/blob/master/src/App.tsx#L17 and same type here https://github.com/ianlai/react-todo-app/blob/master/src/Todo.tsx#L9.
Please put shared types in the same file(ex. types.ts) and import them when necessary, instead of having same shape of type in multiple files.

**Comment by ianlai** [comment]
Separated the common type into types.ts

**Comment by xu3u4** [comment]
👍
