### ISSUE TITLE
Consider to add ESLint

### ISSUE THREAD

**Issue by xu3u4** [ianlai/react-todo-app#3]
[ESLint](https://eslint.org/docs/user-guide/getting-started) can help you format your coding style and detect simple human error. (unused constants, duplicated declaration...etc)

**Comment by ianlai** [comment]
ESLint is running. According to the output when compiling, the output shows 
```
Compiled with warnings.

./src/App.tsx
  Line 2:8:    'logo' is defined but never used            @typescript-eslint/no-unused-vars
  Line 72:15:  'todos' is assigned a value but never used  @typescript-eslint/no-unused-vars

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.
```
The config file of  doesn't show up because `create-react-app` hid it. 
We can see it and get the full control of the configs if we run `npm run eject`.

**Comment by xu3u4** [comment]
Oh, I see. 
I think you can add extra rules if you need.
